// Generated by CoffeeScript 1.6.3
(function() {
  var _gaq=[['_setAccount','UA-3746173-1'],['_trackPageview']];
(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
s.parentNode.insertBefore(g,s)}(document,'script'));;
  var processEvent;

  processEvent = function(refreshEvent) {
    var humanDate, humanTime, nextEvent, outputString, refreshDate, schemaTime;
    refreshDate = moment.unix(refreshEvent.start.timestamp);
    humanDate = refreshDate.format("dddd, MMMM Do");
    humanTime = refreshDate.format("HHmm");
    schemaTime = refreshDate.format("YYYY-MM-DDTHH:mm");
    nextEvent = refreshEvent.summary;
    outputString = " The next event is <strong>" + nextEvent + "</strong> on <time datetime=\"" + schemaTime + "\" class=\"dtstart\"><strong title=\"" + schemaTime + "\" class=\"value-title\">" + humanDate + "</strong> at <strong>" + humanTime + "</strong></time> usually there will be folks arriving from nearer 1800 though.";
    return $('.when-is-refresh').append(outputString);
  };

  jQuery(document).ready(function($) {
    return $.ajax({
      url: 'https://opentechcalendar.co.uk/index.php/group/14/jsonp',
      dataType: 'jsonp',
      success: function(opentechData) {
        var events;
        events = opentechData.data;
        return processEvent(events[0]);
      }
    });
  });

}).call(this);
